@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzk5MzE4ZTBkNWE3NmIwZWIwNzZmOGYiLCJpYXQiOjE3MzgwOTMxNzksImV4cCI6MTczODE3OTU3OX0.NMBsjadHiaz4M6mjYyKhDwnzKKaqEUu3ciG3Ml-XqU8


## GET all notes
GET http://localhost:5000/api/notes
# GET https://warm-reef-41256-e838c74ede11.herokuapp.com/api/notes
Authorization: Bearer {{token}}

### GET a note
GET http://localhost:5000/api/notes/67993d52adec9ff75d56d525
Authorization: Bearer {{token}}


### ADD a note
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My First Note",
  "date": "2024-01-15T00:00:00.000Z",
  "time": "21:24",
  "content": "This is the content of my first note",
  "userId" : "6799318e0d5a76b0eb076f8f"
}
 
### UPDATE a note
PUT http://localhost:5000/api/notes/67993d52adec9ff75d56d525
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My First Note",
  "date": "2024-01-15T00:00:00.000Z",
  "time": "21:30",
  "content": "This is the content of my updated note",
  "userId" : "6799318e0d5a76b0eb076f8f"
}


###DELETE A note
DELETE http://localhost:5000/api/notes/677b0ac6327fb955afa58372
Content-Type: application/json
Authorization: Bearer {{token}}