@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2FiMGVhZTVlNmVhODM1ZDAzMjE5NzEiLCJpYXQiOjE3NjI3MjU1MzAsImV4cCI6MTc2MjgxMTkzMH0.G-Ep6lJj7YXHnX4CY5K7RR8KOnseBb8o2roafS0Knmk


### GET all notes
GET http://localhost:5000/api/notes
# GET https://warm-reef-41256-e838c74ede11.herokuapp.com/api/notes
Authorization: Bearer {{token}}

### GET all user notes
GET http://localhost:5000/api/notes/user/6799318e0d5a76b0eb076f8f
# GET https://warm-reef-41256-e838c74ede11.herokuapp.com/api/notes
Authorization: Bearer {{token}}

### GET a note
GET http://localhost:5000/api/notes/67993d52adec9ff75d56d525
Authorization: Bearer {{token}}


### ADD a note
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My First Note",
  "description": "Installing Docker",
  "date": "Sat Jul 05 2025 18:45:41 GMT+0100 (West Africa Standard Time",
  "userId" : "67ab0eae5e6ea835d0321971",
  "tagIds": [
    "67ab0eaf5e6ea835d0321972"
  ]
}
 
### UPDATE a note
PUT http://localhost:5000/api/notes/690bd2d5201173b09ef456fd
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Dorel's Work",
  "date": "2025-11-05T22:42:28.763Z",
  "time": "21:30",
  "content": "",
  "deleted": false
}


###DELETE A note
DELETE http://localhost:5000/api/notes/677b0ac6327fb955afa58372
Content-Type: application/json
Authorization: Bearer {{token}}