@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2FiMGVhZTVlNmVhODM1ZDAzMjE5NzEiLCJpYXQiOjE3NjI5NjIzNTMsImV4cCI6MTc2MzA0ODc1M30.8MtZ_uX7obiAmeW--JaPyuqn5fNZQg-lscFmpSdU_qI


## GET all artists
GET http://localhost:5000/api/users
# GET https://warm-reef-41256-e838c74ede11.herokuapp.com/api/users
Authorization: Bearer {{token}}

### GET a user
GET http://localhost:5000/api/users/67ab0eae5e6ea835d0321971
Authorization: Bearer {{token}}


### ADD a user
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstname": "Valdez",
  "lastname": "Nzukam",
  "email": "valdez@gmail.com",
  "password": "Root@123"
}
 
### UPDATE a user
PUT http://localhost:5000/api/users/676dee5ca492082befb2031e
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstname": "Valdez",
  "lastname": "Nzukam",
  "email": "mbungaimirabele@gmail.com",
  "password": "root",
}


###DELETE A user
DELETE http://localhost:5000/api/users/677b0ac6327fb955afa58372
Content-Type: application/json
Authorization: Bearer {{token}}

###Login User
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "mbungaifrancesco2@gmail.com",
  "password": "2468Froot"
}

### GET a user by mail
GET http://localhost:5000/api/mail/mbungaifrancesco2@gmail.com